apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoreo
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Monitorear únicamente el namespace mundose
      - job_name: 'mundose'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - mundose
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: mundosemod

      # Configuración para Node Exporter
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - mundose
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app]
            regex: node-exporter

      # Configuración para Nginx Exporter
      - job_name: 'nginx-exporter'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - mundose
        metrics_path: /metrics
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app]
            regex: nginx
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "9113"