apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoreo
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_SERVER_ROOT_URL
          value: "http://dev-env.grupo13.com/services/grafana"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoreo
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoreo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: dev-env.grupo13.com
    http:
      paths:
      - path: /services/grafana(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: grafana
            port:
              number: 3000



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoreo
data:
  grafana.ini: |
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    root_url = http://dev-env.grupo13.com/services/grafana
    serve_from_sub_path = true

    [security]
    admin_user = admin
    admin_password = admin

    [provisioning]
    config_file = /etc/grafana/provisioning/datasources/prometheus-datasource.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoreo
type: Opaque
data:
  admin-user: YWRtaW4=  # admin
  admin-password: YWRtaW4=  # admin